### ISSUE TITLE
Toggle ON/OFF Expanded Widget

### ISSUE THREAD

**Issue by ianeinser** [PavieOlivier/AdvFab#1]
Hi there,
nice work. I have questions. I set AdvFab as Navbar and use onFloatingActionButtonTapped function to toggle it on the expanded widget. However, i would like to toggle it  off back to navbar without depending on RaisedButton. Can you suggest how to do so?

**Comment by PavieOlivier** [comment]
You have to use the controller for this. 
It is mentioned in the documentation.
Sorry for the delay I didn't see this notification

**Comment by cedvdb** [comment]
might be closed
